// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// k_shortest_paths_Cpp
Rcpp::List k_shortest_paths_Cpp(Rcpp::DataFrame graph_df, Rcpp::IntegerVector start_vertex, Rcpp::IntegerVector end_vertex, Rcpp::IntegerVector k, Rcpp::IntegerVector vertex_num, bool verbose);
RcppExport SEXP _yenpathy_k_shortest_paths_Cpp(SEXP graph_dfSEXP, SEXP start_vertexSEXP, SEXP end_vertexSEXP, SEXP kSEXP, SEXP vertex_numSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type graph_df(graph_dfSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type start_vertex(start_vertexSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type end_vertex(end_vertexSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type vertex_num(vertex_numSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(k_shortest_paths_Cpp(graph_df, start_vertex, end_vertex, k, vertex_num, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_yenpathy_k_shortest_paths_Cpp", (DL_FUNC) &_yenpathy_k_shortest_paths_Cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_yenpathy(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
