# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shortest_path <- function(start_vertex, end_vertex, vertex_num, graph_df) {
    .Call(`_yenpathy_shortest_path`, start_vertex, end_vertex, vertex_num, graph_df)
}

