# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.k_shortest_paths_Cpp <- function(graph_df, start_vertex, end_vertex, k, vertex_num, verbose = FALSE) {
    .Call(`_yenpathy_k_shortest_paths_Cpp`, graph_df, start_vertex, end_vertex, k, vertex_num, verbose)
}

